files.extend-exclude = ["pytket/docs/pytket-docs-theming/**"]


[default.extend-identifiers]
Aer = "Aer"
AerBackend = "AerBackend"
AerStateBackend = "AerStateBackend"
AerUnitaryBackend = "AerUnitaryBackend"
AerDensityMatrixBackend = "AerDensityMatrixBackend"
aer = "aer"
qiskit_aer = "qiskit_aer"
anc = "anc"
arange = "arange"
aer_unitary_b = "aer_unitary_b"
aer_b = "aer_b"
noisy_aer_b = "noisy_aer_b"
aer_state_b = "aer_state_b"
args_ser = "arg_ser"
IY = "IY"
iy = "iy"
PNGs = "PNGs"
NDArray = "NDArray"
pattern_nd = "pattern_nd"
pn = "pn"
add_pn_unitary = "add_pn_unitary"
bc5623349aab2c121d0ede3b23124534452312ab56_12369abcde = "bc5623349aab2c121d0ede3b23124534452312ab56_12369abcde"
01213234567869a6a76b781776ac6d17a71ef1gh17f1a7iaa7j878j8a7haa6ac = "01213234567869a6a76b781776ac6d17a71ef1gh17f1a7iaa7j878j8a7haa6ac"
012324025605576869ab1c0d5eefgf6g066h2i6j02016k2i0l0mek066b0d6ngo6g56 = "012324025605576869ab1c0d5eefgf6g066h2i6j02016k2i0l0mek066b0d6ngo6g56"
target_nd = "target_nd"
BRIDGEs = "BRIDGEs"
ot = "ot"

[default.extend-words]
Braket = "Braket"
braket = "braket"
AAS = "AAS"
Strat = "Strat"
strat = "strat"
typ = "typ"
NDArray = "NDArray"
classicals = "classicals"
BRIDGEs = "BRIDGEs"
Childs = "Childs"
pn = "pn"
add_pn_unitary = "add_pn_unitary"
pattern_nd = "pattern_nd"
target_nd = "target_nd"
args_ser = "args_ser"
tabl = "tabl"
