files.extend-exclude = [
    "pytket/docs/pytket-docs-theming/**",
    "tket/test/src/TokenSwapping/Data/**",
    "libs/tktokenswap/test/src/Data/**",
]


[default.extend-identifiers]
Aer = "Aer"
AerBackend = "AerBackend"
AerStateBackend = "AerStateBackend"
AerUnitaryBackend = "AerUnitaryBackend"
AerDensityMatrixBackend = "AerDensityMatrixBackend"
aer = "aer"
qiskit_aer = "qiskit_aer"
anc = "anc"
arange = "arange"
aer_unitary_b = "aer_unitary_b"
aer_b = "aer_b"
noisy_aer_b = "noisy_aer_b"
aer_state_b = "aer_state_b"
arg_ser = "arg_ser"
args_ser = "args_ser"
IY = "IY"
iy = "iy"
PNGs = "PNGs"
NDArray = "NDArray"
numer = "numer"
pattern_nd = "pattern_nd"
pn = "pn"
add_pn_unitary = "add_pn_unitary"
non_trivials = "non_trivials"
target_nd = "target_nd"
BRIDGEs = "BRIDGEs"
ot = "ot"
ccontrol_pred = "ccontrol_pred"

[default.extend-words]
Braket = "Braket"
braket = "braket"
AAS = "AAS"
Strat = "Strat"
strat = "strat"
typ = "typ"
NDArray = "NDArray"
classicals = "classicals"
BRIDGEs = "BRIDGEs"
Childs = "Childs"
pn = "pn"
add_pn_unitary = "add_pn_unitary"
pattern_nd = "pattern_nd"
target_nd = "target_nd"
args_ser = "args_ser"
tabl = "tabl"
