files.extend-exclude = ["pytket/docs/pytket-docs-theming/**"]


[default.extend-identifiers]
Aer = "Aer"
AerBackend = "AerBackend"
AerStateBackend = "AerStateBackend"
AerUnitaryBackend = "AerUnitaryBackend"
AerDensityMatrixBackend = "AerDensityMatrixBackend"
aer = "aer"
qiskit_aer = "qiskit_aer"
anc = "anc"
arange = "arange"
aer_unitary_b = "aer_unitary_b"
aer_b = "aer_b"
noisy_aer_b = "noisy_aer_b"
aer_state_b = "aer_state_b"
args_ser = "arg_ser"
IY = "IY"
iy = "iy"
PNGs = "PNGs"
NDArray = "NDArray"
pattern_nd = "pattern_nd"
pn = "pn"

[default.extend-words]
Braket = "Braket"
braket = "braket"
AAS = "AAS"
Strat = "Strat"
strat = "strat"
typ = "typ"
NDArray = "NDArray"
classicals = "classicals"
BRIDGEs = "BRIDGEs"
Childs = "Childs"
