#!/usr/bin/env python

# Extract the label (including version) from the json output of `conan create`.
# Conan 2 is assumed.

# Usage: ./libver <json_file> <package_name>

import json
import sys

jsonfile = sys.argv[1]
name = sys.argv[2]

with open(jsonfile, "r") as f:
    info = json.load(f)

nodes = [node for node in info["graph"]["nodes"] if node["ref"].startswith(f"{name}/")]
assert len(nodes) == 1
node = nodes[0]
print(node["label"])
