OPENQASM 2.0;
include "hqslib1.inc";

qreg q[1];
creg a[2];
creg b[3];
creg c[4];
creg d[1];
creg tk_SCRATCH_BIT[7];
creg tk_SCRATCH_BITREG_0[64];
c = 2;
tk_SCRATCH_BITREG_0[0] = b[0] & a[0];
tk_SCRATCH_BITREG_0[1] = b[1] & a[1];
c[0] = a[0];
c[1] = a[1];
if(b!=2) tk_SCRATCH_BIT[6] = b[1] & a[1];
c[0] = tk_SCRATCH_BITREG_0[0] | d[0];
if(b!=2) c[1] = tk_SCRATCH_BIT[6] | a[0];
tk_SCRATCH_BIT[6] = 1;
d[0] = a[0] ^ tk_SCRATCH_BIT[6];
if(c>=2) h q[0];
a = CCE(a, b);
if(c<=2) h q[0];
CCE(c);
if(c<=1) h q[0];
if(c>=3) h q[0];
if(c!=2) h q[0];
if(d[0]==1) rx(1.0*pi) q[0];
