from typing import Union

import pytket._tket.circuit
import sympy

def _BRIDGE() -> pytket._tket.circuit.Circuit: ...
def _BRIDGE_using_CX_0() -> pytket._tket.circuit.Circuit: ...
def _BRIDGE_using_CX_1() -> pytket._tket.circuit.Circuit: ...
def _C3X_normal_decomp() -> pytket._tket.circuit.Circuit: ...
def _C4X_normal_decomp() -> pytket._tket.circuit.Circuit: ...
def _CCX() -> pytket._tket.circuit.Circuit: ...
def _CCX_modulo_phase_shift() -> pytket._tket.circuit.Circuit: ...
def _CCX_normal_decomp() -> pytket._tket.circuit.Circuit: ...
def _CH_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CRx_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CRx_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CRy_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CRy_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CRz_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CRz_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CSWAP_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CSX_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CSXdg_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CU1_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CU1_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CU3_using_CX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _CV_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CVdg_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CX() -> pytket._tket.circuit.Circuit: ...
def _CX_S_CX_reduced() -> pytket._tket.circuit.Circuit: ...
def _CX_S_V_XC_reduced() -> pytket._tket.circuit.Circuit: ...
def _CX_VS_CX_reduced() -> pytket._tket.circuit.Circuit: ...
def _CX_V_CX_reduced() -> pytket._tket.circuit.Circuit: ...
def _CX_V_S_XC_reduced() -> pytket._tket.circuit.Circuit: ...
def _CX_XC_reduced() -> pytket._tket.circuit.Circuit: ...
def _CX_using_ECR() -> pytket._tket.circuit.Circuit: ...
def _CX_using_TK2() -> pytket._tket.circuit.Circuit: ...
def _CX_using_XXPhase_0() -> pytket._tket.circuit.Circuit: ...
def _CX_using_XXPhase_1() -> pytket._tket.circuit.Circuit: ...
def _CX_using_ZZMax() -> pytket._tket.circuit.Circuit: ...
def _CX_using_ZZPhase() -> pytket._tket.circuit.Circuit: ...
def _CX_using_flipped_CX() -> pytket._tket.circuit.Circuit: ...
def _CY_using_CX() -> pytket._tket.circuit.Circuit: ...
def _CZ_using_CX() -> pytket._tket.circuit.Circuit: ...
def _ECR_using_CX() -> pytket._tket.circuit.Circuit: ...
def _ESWAP_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _ESWAP_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _FSim_using_CX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _FSim_using_TK2(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _H_CZ_H() -> pytket._tket.circuit.Circuit: ...
def _ISWAP_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _ISWAP_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _NPhasedX_using_PhasedX(arg0: int, arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _PhasedISWAP_using_CX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _PhasedISWAP_using_TK2(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _SWAP_using_CX_0() -> pytket._tket.circuit.Circuit: ...
def _SWAP_using_CX_1() -> pytket._tket.circuit.Circuit: ...
def _TK1_to_PhasedXRz(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK1_to_RzH(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK1_to_RzRx(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK1_to_RzSX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK1_to_TK1(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_3xCX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_CX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_CX_and_swap(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_TK2_or_swap(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_ZZMax(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_ZZMax_and_swap(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_ZZPhase(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_ZZPhase_and_swap(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _TK2_using_normalised_TK2(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float], arg2: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _X() -> pytket._tket.circuit.Circuit: ...
def _X1_CX() -> pytket._tket.circuit.Circuit: ...
def _XXPhase3_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _XXPhase3_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _XXPhase_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _XXPhase_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _YYPhase_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _YYPhase_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _Z0_CX() -> pytket._tket.circuit.Circuit: ...
def _ZZMax_using_CX() -> pytket._tket.circuit.Circuit: ...
def _ZZPhase_using_CX(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _ZZPhase_using_TK2(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _approx_TK2_using_1xCX() -> pytket._tket.circuit.Circuit: ...
def _approx_TK2_using_1xZZPhase(arg0: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _approx_TK2_using_2xCX(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _approx_TK2_using_2xZZPhase(arg0: Union[sympy.Expr,float], arg1: Union[sympy.Expr,float]) -> pytket._tket.circuit.Circuit: ...
def _ladder_down() -> pytket._tket.circuit.Circuit: ...
def _ladder_down_2() -> pytket._tket.circuit.Circuit: ...
def _ladder_up() -> pytket._tket.circuit.Circuit: ...
def _two_Rz1() -> pytket._tket.circuit.Circuit: ...
