from typing import List

import pytket._tket.circuit

class AASLabellingMethod(RoutingMethod):
    def __init__(self) -> None: ...

class AASRouteRoutingMethod(RoutingMethod):
    def __init__(self, aaslookahead: int) -> None: ...

class BoxDecompositionRoutingMethod(RoutingMethod):
    def __init__(self) -> None: ...

class LexiLabellingMethod(RoutingMethod):
    def __init__(self) -> None: ...

class LexiRouteRoutingMethod(RoutingMethod):
    def __init__(self, lookahead: int = ...) -> None: ...

class MappingManager:
    def __init__(self, architecture) -> None: ...
    def route_circuit(self, circuit: pytket._tket.circuit.Circuit, routing_methods: List[RoutingMethod]) -> bool: ...

class MultiGateReorderRoutingMethod(RoutingMethod):
    def __init__(self, max_depth: int = ..., max_size: int = ...) -> None: ...

class RoutingMethod:
    def __init__(self) -> None: ...

class RoutingMethodCircuit(RoutingMethod):
    def __init__(self, route_subcircuit, max_size: int, max_depth: int) -> None: ...
