install-dev:
    poetry install
    poetry run pip install ../.

install:
    poetry install
    poetry run pip install -U pytket

build:
    poetry run bash ./build-docs.sh

serve: build
    npm exec serve build

clean:
    rm -rf jupyter_execute
    rm -rf .jupyter_cache
    rm -rf build
    rm -rf _static
    rm -rf quantinuum-sphinx
    rm -f conf.py