#!/usr/bin/env python3

import importlib
from pathlib import Path
import pkgutil
import pytket
from nanobind.stubgen import StubGen

def gen_module_stubs(modname, output_file):
    mod_imported = importlib.import_module(f"pytket._tket.{modname}")
    sg = StubGen(
        module=mod_imported,
        output_file=output_file
    )
    sg.put(mod_imported)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(sg.get())

if __name__ == "__main__":
    pytket_dir = Path(__file__).parent.parent.resolve()
    for mod in pkgutil.iter_modules(pytket._tket.__path__):
        modname = mod.name
        if not modname.startswith("lib"):
            print(f"Generate {modname}.pyi")
            gen_module_stubs(modname, output_file=pytket_dir/"pytket"/"_tket"/f"{modname}.pyi")
