#!/usr/bin/env python3

import importlib
import os
from pathlib import Path
import pkgutil
import re

from stubgen import StubGen
import pytket


def replace_in_file_string(
    stub: str, matcher: str, replacement: str
) -> tuple[str, int]:
    split_text = re.split(matcher, stub)
    modified_text = replacement.join(split_text)
    return modified_text, len(split_text) - 1


def handle_args_kwargs_types(stub: str) -> str:
    modified, n_args = replace_in_file_string(stub, "\\*args(?=[^:])", "*args: Any")
    modified, n_kwargs = replace_in_file_string(
        modified, "\\*\\*kwargs(?=[^:])", "**kwargs: Any"
    )
    n_total = n_args + n_kwargs
    if n_total > 0 and not re.search("from typing import .*Any", modified):
        modified = "from typing import Any" + os.linesep + modified
    return modified


def handle_optype_default(stub: str) -> str:
    modified, n = replace_in_file_string(
        stub, " = OpType\\.", " = pytket._tket.circuit.OpType."
    )
    return modified


def handle_to_dict(stub: str) -> str:
    modified, n = replace_in_file_string(
        stub, "def to_dict\\(self\\) -> JSON:", "def to_dict(self) -> dict:"
    )
    return modified


def handle_object_type(stub: str) -> str:
    modified, n = replace_in_file_string(
        stub,
        "Callable\\[\\[pytket\\._tket\\.predicates\\.CompilationUnit, object\\], None\\]",
        "Callable[[pytket._tket.predicates.CompilationUnit, Any], None]",
    )
    return modified


def gen_module_stubs(modname, output_file):
    mod_imported = importlib.import_module(f"pytket._tket.{modname}")
    sg = StubGen(
        module=mod_imported,
        private_exceptions={
            "_add_w_register",
            "_add_wasm",
            "_classical_eval",
            "_current",
            "_dag_data",
            "_DEBUG_ONE_REG_PREFIX",
            "_DEBUG_ZERO_REG_PREFIX",
            "_n_vertices",
            "_TEMP_BIT_NAME",
            "_TEMP_BIT_REG_BASE",
            "_TEMP_REG_SIZE",
        },
        output_file=output_file,
    )
    sg.put(mod_imported)
    with open(output_file, "w", encoding="utf-8") as f:
        stub: str = sg.get()
        stub = handle_args_kwargs_types(stub)
        stub = handle_optype_default(stub)
        stub = handle_to_dict(stub)
        stub = handle_object_type(stub)
        f.write(stub)


if __name__ == "__main__":
    pytket_dir = Path(__file__).parent.parent.resolve()
    # for mod in pkgutil.iter_modules(pytket._tket.__path__):
    #     modname = mod.name
    for modname in [
        "architecture",
        # "circuit", # 206
        "circuit_library",
        "logging",
        "mapping",
        "partition",
        # "passes", # 48
        "pauli",
        "placement",
        "predicates",
        "tableau",
        "tailoring",
        "transform",
        # "unit_id", # 55
        "utils_serialization",
        "zx",
    ]:
        if not modname.startswith("lib"):
            print(f"Generate {modname}.pyi")
            gen_module_stubs(
                modname, output_file=pytket_dir / "pytket" / "_tket" / f"{modname}.pyi"
            )
