name: Automated Benchmarks

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:

  Run-Benchmakrs:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pytket-benchmarking
        run: pip install --pre --index-url https://github_actions:${{ secrets.PRIVATE_PYPI_PASS }}@cqcpythonrepository.azurewebsites.net/simple/ pytket-benchmarking