name: Automated Benchmarks

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:

  build_wheels:
    name: Build manylinux
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Tket
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    
    - name: Set up container
      run: |
        docker create --name linux_build -i -v /:/host quay.io/pypa/manylinux_2_28_x86_64:latest /bin/bash
        docker cp . linux_build:/tket/
    
    - name: Run build
      run: |
        docker start linux_build
        docker exec -e PY_TAG="cp311-cp311" -e CONAN_PROFILE=linux-x86_64-gcc12 linux_build /bin/bash -c "/tket/.github/workflows/linuxbuildwheel"
        mkdir wheelhouse
        docker cp linux_build:/tket/pytket/audited/. wheelhouse/
    
    - uses: actions/upload-artifact@v4
      with:
        name: Linux_3.11_wheel
        path: wheelhouse/

  Run-Benchmakrs:
    name: Run Benchmarks
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Tket
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install pytket-benchmarking
        run: pip install --pre --index-url https://github_actions:${{ secrets.PRIVATE_PYPI_PASS }}@cqcpythonrepository.azurewebsites.net/simple/ pytket_benchmarking==0.0.2
      
      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The results of the benchmarking are...'
            })
