#! /usr/bin/env bash
set -evx

# Edit this list as required:
PACKAGES="catch2/3.3.2@ \
          rapidcheck/cci.20220514@"

for PACKAGE in ${PACKAGES}
do
    conan remove -c "${PACKAGE}"
    echo "Installing:" ${PACKAGE} "(in two configurations) ..."
    conan install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True
    conan install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True -o tklog/*:shared=True -o tket/*:shared=True
done

for PACKAGE in ${PACKAGES}
do
    echo "Uploading:" ${PACKAGE} "..."
    conan upload ${PACKAGE} -r=tket-libs
done

echo "Done."
