#!/bin/bash

# Copyright 2019-2022 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -u

cd pytket/docs
rm -rf build
# Capture any unexpected errors or warnings.
# The expected warnings are:
# - "Inline strong start-string without end-string."
# - "Inline emphasis start-string without end-string."
make html 1>out.txt 2>err.txt
cat out.txt err.txt
ERRS=`cat err.txt | grep -v "start-string without end-string"`
if [[ ! -z $ERRS ]]
then
    echo "Docs build failed."
    exit 1
fi
