#!/bin/bash

# Copyright 2019-2022 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

cd $GITHUB_WORKSPACE/pytket
export PYVER=`python -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'`
python -m pip uninstall -y pytket
python -m pip install -U pip build delocate
python -m build --outdir "$GITHUB_WORKSPACE/tmp/tmpwheel_${PYVER}"
delocate-wheel -v -w "$GITHUB_WORKSPACE/wheelhouse/${PYVER}/" "$GITHUB_WORKSPACE/tmp/tmpwheel_${PYVER}/pytket-"*".whl"
