#! /usr/bin/env bash
set -ex

# Edit this list as required:
PACKAGES="b2/4.9.2@ \
          boost/1.80.0@ \
          bzip2/1.0.8@ \
          catch2/3.1.0@ \
          eigen/3.4.0@ \
          gmp/6.2.1@ \
          libbacktrace/cci.20210118@ \
          libiconv/1.17@ \
          nlohmann_json/3.11.2@ \
          pybind11_json/0.2.12@ \
          rapidcheck/cci.20220514@ \
          symengine/0.9.0@ \
          zlib/1.2.12@"

BUILD_TYPES="Release Debug"

conan remote add conan-center https://center.conan.io --force

for PACKAGE in ${PACKAGES}
do
    conan remove -f ${PACKAGE} || true
    for BUILD_TYPE in ${BUILD_TYPES}
    do
        echo "Installing:" ${PACKAGE} ${BUILD_TYPE} "..."
        conan install ${PACKAGE} --profile=tket -s build_type=${BUILD_TYPE} --build=missing --update -r=conan-center
    done
done

for PACKAGE in ${PACKAGES}
do
    echo "Uploading:" ${PACKAGE} "..."
    conan upload ${PACKAGE} --all -r=tket-libs
done

conan remote remove conan-center

echo "Done."
