#!/usr/bin/env python

# Check that the expected tket version requirement is present for:
# - tket-tests
# - tket-proptests
# - pytket
# Usage: check-tket-reqs <version>
# E.g.: check-tket-reqs 1.0.2

import json
import os
import subprocess
import sys
import conan

version = sys.argv[1]

conanfile_path = os.path.join(".", "pytket", "conanfile.py")

conan_ver = conan.conan_version.major.value

jsondump = "conaninfo.json"

assert conan_ver == 2
with open(jsondump, "w") as f:
    subprocess.call(["conan", "graph", "info", conanfile_path, "--format", "json"], stdout=f)
with open(jsondump) as f:
    info = json.load(f)
os.remove(jsondump)
assert any(
    node["ref"].startswith(f"tket/{version}@tket/stable")
    for _, node in info["graph"]["nodes"].items()
)
