#!/usr/bin/env python3

# Usage:
#
# compare-coverage <file> <file1>
#
# where each file contains a couple of lines of text such as:
#
# lines: 87.5% (17090 out of 19537)
# branches: 46.4% (23147 out of 49885)
#
# Returns status 0 if `file1` is at least as good as `file` on both scores, otherwise
# returns status 1.

import sys


def extract_num_from_percent(word):
    assert word[-1] == "%"
    return float(word[:-1])


def get_percentages(summary):
    words = summary.split()
    assert words[0] == "lines:"
    assert words[6] == "branches:"
    return extract_num_from_percent(words[1]), extract_num_from_percent(words[7])


def compare(summary, summary1):
    print("Comparing coverage:")
    print()
    print("Old:")
    print(summary)
    print("New:")
    print(summary1)

    lpercent, bpercent = get_percentages(summary)
    lpercent1, bpercent1 = get_percentages(summary1)

    if lpercent1 < lpercent or bpercent1 < bpercent:
        print("Percentage line or branch coverage has decreased.")
        exit(1)


if __name__ == "__main__":
    file, file1 = sys.argv[1:3]
    with open(file, "r") as f:
        summary = f.read()
    with open(file1) as f:
        summary1 = f.read()
    compare(summary, summary1)
