#!/usr/bin/env bash

set -ex

conan profile new tket --detect --force
if [ "$(uname -s)" == "Linux" ]; then
    conan profile update settings.compiler.libcxx=libstdc++11 tket
fi
conan profile update options.tklog:shared=True tket
conan profile update options.tket:shared=True tket
conan remote clean
conan remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs
