name: Deploy tket C++ documentation

on:
  push:
    branches:
      - develop
    paths:
      - 'tket/src/**'

jobs:
  build_docs:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Install Doxygen
      run: sudo apt update && sudo apt install -y doxygen graphviz
    - name: Build Doxygen docs
      run: cd tket && doxygen
    - name: Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: tket_docs
        path: tket/doc/html/
  publish_docs:
    needs: build_docs
    concurrency: gh_pages
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Download artefact
      uses: actions/download-artifact@v3
      with:
        name: tket_docs
        path: api/
    - name: Configure git
      run: |
        git config --global user.email "tket-bot@cambridgequantum.com"
        git config --global user.name  "«$GITHUB_WORKFLOW» github action"
    - name: Remove old docs
      run: git rm -r docs/tket/api
    - name: Add generated docs to repository
      run: |
        mv api/ docs/tket/
        git add -f docs/tket/api
        git commit --allow-empty -m "Add generated tket C++ documentation."
    - name: Publish docs
      run:  git push origin gh-pages:gh-pages
