name: New issue

on:
  issues:
    types: [opened]

jobs:
  jira_issue:
    name: Create Jira issue
    runs-on: ubuntu-20.04
    steps:
    - name: Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create Bug
      uses: atlassian/gajira-create@v2.0.1
      if: contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: TKET
        issuetype: Bug
        summary: «${{ github.event.issue.title }}»
        description: ${{ github.event.issue.html_url }}
    - name: Create Task
      uses: atlassian/gajira-create@v2.0.1
      if: "! contains(github.event.issue.labels.*.name, 'bug')"
      with:
        project: TKET
        issuetype: Task
        summary: «${{ github.event.issue.title }}»
        description: ${{ github.event.issue.html_url }}
