#!/bin/bash

# Copyright 2019-2023 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

export PYEX=/opt/python/${PY_TAG}/bin/python
for whl in `ls /tket/wheelhouse/`
do
    ${PYEX} -m pip install /tket/wheelhouse/${whl}
done
cd /tket/pytket/tests
${PYEX} -m pip install -r requirements.txt
/opt/python/${PY_TAG}/bin/pytest --ignore=simulator/
