#!/bin/bash

# Copyright 2019-2023 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

# Choose a Python to install conan
export PYBIN=/opt/python/cp310-cp310/bin

${PYBIN}/pip install conan~=1.53

export CONAN_CMD=${PYBIN}/conan

export CONAN_REVISIONS_ENABLED=1

cd /tket

${CONAN_CMD} profile new tket --detect

${CONAN_CMD} remote clean
${CONAN_CMD} remote add conan-center https://center.conan.io --force

# Edit this list as required:
PACKAGES="b2/4.9.2@ \
          boost/1.81.0@ \
          bzip2/1.0.8@ \
          eigen/3.4.0@ \
          gmp/6.2.1@ \
          libbacktrace/cci.20210118@ \
          libiconv/1.17@ \
          m4/1.4.19@ \
          nlohmann_json/3.11.2@ \
          pybind11_json/0.2.12@ \
          symengine/0.9.0@ \
          zlib/1.2.13@"

for PACKAGE in ${PACKAGES}
do
    echo "Installing:" ${PACKAGE} "..."
    ${CONAN_CMD} remove -f ${PACKAGE} || true
    ${CONAN_CMD} install ${PACKAGE} --profile=tket -s build_type=Release --build=missing --update -r=conan-center
done

${CONAN_CMD} remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs

${CONAN_CMD} user -p ${JFROG_ARTIFACTORY_TOKEN_2} -r tket-libs ${JFROG_ARTIFACTORY_USER_2}

for PACKAGE in ${PACKAGES}
do
    echo "Uploading:" ${PACKAGE} "..."
    ${CONAN_CMD} upload ${PACKAGE} --all -r=tket-libs
done

echo "Done."
