#!/bin/bash

# Copyright 2019-2024 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

# Choose a Python to install conan
export PYBIN=/opt/python/cp310-cp310/bin

${PYBIN}/pip install --upgrade pip
${PYBIN}/pip install conan~=2.0

export CONAN_CMD=${PYBIN}/conan

${CONAN_CMD} profile detect
DEFAULT_PROFILE_PATH=`${CONAN_CMD} profile path default`
PROFILE_PATH=./conan-profiles/${CONAN_PROFILE}
diff ${DEFAULT_PROFILE_PATH} ${PROFILE_PATH} || true
cp ${PROFILE_PATH} ${DEFAULT_PROFILE_PATH}
${CONAN_CMD} remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs --index 0

${CONAN_CMD} remote login -p ${JFROG_ARTIFACTORY_TOKEN_3} tket-libs ${JFROG_ARTIFACTORY_USER_3}

${CONAN_CMD} create ${TKLIB} -o boost/*:header_only=True --build=missing --user=tket --channel=stable --format json > ${TKLIB}.json

LIB_LABEL=$(${PYBIN}/python ./libver ${TKLIB}.json ${TKLIB})

if [ ${UPLOAD_PACKAGE} == "YES" ]
then
    ${CONAN_CMD} upload ${LIB_LABEL} -r=tket-libs
fi
