#!/bin/bash

# Copyright 2019-2023 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

# Choose a Python to install conan
export PYBIN=/opt/python/cp310-cp310/bin

${PYBIN}/pip install conan

export CONAN_CMD=${PYBIN}/conan

cd /tket

${CONAN_CMD} profile detect
${CONAN_CMD} remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs

# Edit this list as required:
PACKAGES="boost/1.81.0@ \
          catch2/3.3.0@ \
          gmp/6.2.1@ \
          symengine/0.9.0@ \
          tklog/0.3.3@tket/stable \
          tkassert/0.3.3@tket/stable \
          tkrng/0.3.3@tket/stable \
          tktokenswap/0.3.3@tket/stable \
          tkwsm/0.3.3@tket/stable"

for PACKAGE in ${PACKAGES}
do
    echo "Installing:" ${PACKAGE} "(in two configurations) ..."
    ${CONAN_CMD} install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True
    ${CONAN_CMD} install --requires ${PACKAGE} --build=missing -o boost/*:header_only=True -o tklog/*:shared=True -o tket/*:shared=True
done

${CONAN_CMD} remote login -p ${JFROG_ARTIFACTORY_TOKEN_3} tket-libs ${JFROG_ARTIFACTORY_USER_3}

for PACKAGE in ${PACKAGES}
do
    echo "Uploading:" ${PACKAGE} "..."
    ${CONAN_CMD} upload ${PACKAGE} -r=tket-libs
done

echo "Done."
