#!/bin/bash

# Copyright 2019-2023 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

# Choose a Python to install conan
export PYBIN=/opt/python/cp39-cp39/bin

export CONAN_REVISIONS_ENABLED=1

${PYBIN}/pip install --upgrade pip
${PYBIN}/pip install conan~=1.53

export CONAN_CMD=${PYBIN}/conan

${CONAN_CMD} profile new tket --detect

${CONAN_CMD} remote clean
${CONAN_CMD} remote add tket-libs https://quantinuumsw.jfrog.io/artifactory/api/conan/tket1-libs

${CONAN_CMD} user -p ${JFROG_ARTIFACTORY_TOKEN_2} -r tket-libs ${JFROG_ARTIFACTORY_USER_2}

LIB_VER=$(${CONAN_CMD} inspect --raw version ${TKLIB})

${CONAN_CMD} create --profile=tket -o ${TKLIB}:shared=False ${TKLIB} tket/stable
${CONAN_CMD} create --profile=tket -o ${TKLIB}:shared=True ${TKLIB} tket/stable

if [ ${UPLOAD_PACKAGE} == "YES" ]
then
    ${CONAN_CMD} upload ${TKLIB}/${LIB_VER}@tket/stable --all -r=tket-libs
else
    ${CONAN_CMD} upload ${TKLIB}/${LIB_VER}@tket/stable --all -r=tket-libs --skip-upload
fi
