#!/bin/bash

# Copyright 2019-2021 Cambridge Quantum Computing
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -evu

# Choose a Python to install conan
export PYBIN=/opt/python/cp39-cp39/bin

${PYBIN}/pip install conan

export CONAN_CMD=${PYBIN}/conan

cd /tket

${CONAN_CMD} profile new tket --detect
${CONAN_CMD} create --profile=tket recipes/symengine
${CONAN_CMD} create --profile=tket --test-folder=None recipes/tket
${CONAN_CMD} create --profile=tket --test-folder=None recipes/pybind11

cd /tket/pytket
mkdir wheelhouse
mkdir audited

for pyX in $PY_VERS
do
    cd /tket/pytket
    export PYEX=/opt/python/${pyX}/bin/python
    export PYVER=`${PYEX} -c 'import sys; print(".".join(map(str, sys.version_info[:3])))'`
    ${PYEX} -m pip install -U pip setuptools_scm
    ${PYEX} setup.py bdist_wheel -d "tmpwheel_${PYVER}"
    auditwheel repair "tmpwheel_${PYVER}/pytket-"*".whl" -w "audited/${PYVER}/"
done
