name: Deploy bubble coverage report

on:
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 4 * * 6'

jobs:

  linux:
    name: Generate coverage report
    runs-on: ubuntu-20.04
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current time
      uses: srfrnk/current-time@v1.1.0
      id: current_time
      with:
        format: YYYYMMDDHHmmss
    - name: Cache ccache data
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-tket-ccache-${{ steps.current_time.outputs.formattedTime }}
        restore-keys: |
          ${{ runner.os }}-tket-ccache-
    - name: Install conan
      id: conan
      # urllib3 because of TKET-865 (remove when conan fixes its dependencies)
      run: |
        pip install urllib3==1.25.11 conan
        conan_cmd=/home/runner/.local/bin/conan
        ${conan_cmd} profile new tket --detect
        ${conan_cmd} profile update settings.compiler.libcxx=libstdc++11 tket
        ${conan_cmd} profile update settings.build_type=Debug tket
        echo "CONAN_CMD=${conan_cmd}" >> $GITHUB_ENV
    - name: Install ninja and ccache
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build ccache
    - name: Build tket
      run: |
        ${CONAN_CMD} install recipes/tket --install-folder=build/tket --profile=tket -o tket:profile_coverage=True
        ${CONAN_CMD} build recipes/tket --configure --build-folder=build/tket --source-folder=bubble/src
        ${CONAN_CMD} build recipes/tket --build --build-folder=build/tket
        ${CONAN_CMD} export-pkg recipes/tket -f --build-folder=build/tket --source-folder=bubble/src
    - name: Build tket tests
      run: |
        ${CONAN_CMD} install recipes/tket-tests --install-folder=build/tket-tests --profile=tket -o tket-tests:with_coverage=True
        ${CONAN_CMD} build recipes/tket-tests --configure --build-folder=build/tket-tests --source-folder=bubble/tests
        ${CONAN_CMD} build recipes/tket-tests --build --build-folder=build/tket-tests
    - name: Install runtime test requirements
      run: |
        sudo apt-get install texlive texlive-latex-extra latexmk
        mkdir -p ~/texmf/tex/latex
        wget http://mirrors.ctan.org/graphics/pgf/contrib/quantikz/tikzlibraryquantikz.code.tex -P ~/texmf/tex/latex
    - name: Run tket tests
      run: ./build/tket-tests/bin/test_tket
    - name: Configure git
      run: |
        git config --global user.email "tket-bot@cambridgequantum.com"
        git config --global user.name  "«$GITHUB_WORKFLOW» github action"
    - name: Check out gh-pages branch
      run:  git checkout gh-pages
    - name: Remove old report
      run: git rm -r --ignore-unmatch bubble/test-coverage
    - name: Install gcovr
      run: sudo apt-get install gcovr
    - name: Build coverage report
      run: |
        mkdir bubble/test-coverage
        gcovr --html --html-details -r ./bubble/src/ --object-directory `pwd`/build/tket/CMakeFiles/tket.dir -o bubble/test-coverage/index.html
    - name: Add report to repository
      run: |
        git add -f bubble/test-coverage
        git commit --allow-empty -m "Add generated coverage report."
    - name: Publish report
      run: git push origin gh-pages:gh-pages
