name: Release

on:
  push:
    branches:
      - 'ae/test-includes.1'

jobs:
  build_Linux_wheels:
    name: Build manylinux
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python3-version: ['12']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up container
      run: |
        docker create --name linux_build -i -v /:/host quay.io/pypa/manylinux_2_28_x86_64:latest /bin/bash
        docker cp . linux_build:/tket/
    - name: Run build
      run: |
        docker start linux_build
        docker exec -e PY_TAG="cp3${{ matrix.python3-version }}-cp3${{ matrix.python3-version }}" -e CONAN_PROFILE=linux-x86_64-gcc12 linux_build /bin/bash -c "/tket/.github/workflows/linuxbuildwheel"
        mkdir wheelhouse
        docker cp linux_build:/tket/pytket/audited/. wheelhouse/
    - uses: actions/upload-artifact@v4
      with:
        name: Linux_3.${{ matrix.python3-version }}_wheel
        path: wheelhouse/

  build_Linux_aarch64_wheels:
    name: Build manylinux aarch64
    # We need the one with 12GB RAM to build pytket.
    runs-on: 'buildjet-8vcpu-ubuntu-2204-arm'
    strategy:
      matrix:
        python3-version: ['12']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up container
      run: |
        docker create --name linux_build -i -v /:/host quay.io/pypa/manylinux_2_28_aarch64:latest /bin/bash
        docker cp . linux_build:/tket/
    - name: Run build
      run: |
        docker start linux_build
        docker exec -e PY_TAG="cp3${{ matrix.python3-version }}-cp3${{ matrix.python3-version }}" -e CONAN_PROFILE=linux-armv8-gcc12 linux_build /bin/bash -c "/tket/.github/workflows/linuxbuildwheel"
        mkdir wheelhouse
        docker cp linux_build:/tket/pytket/audited/. wheelhouse/
    - uses: actions/upload-artifact@v4
      with:
        name: Linux_aarch64_3.${{ matrix.python3-version }}_wheel
        path: wheelhouse/

  test_linux_wheels:
    name: Test linux wheels
    needs: build_Linux_wheels
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python3-version: ['12']
    steps:
      - name: Set up Python 3.${{ matrix.python3-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.${{ matrix.python3-version }}"
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: Linux_3.${{ matrix.python3-version }}_wheel
          path: wheelhouse/
      - name: Install wheel
        run: pip install wheelhouse/pytket-*.whl
      - uses: actions/checkout@v4
        with:
          path: tket
      - name: Setup tests
        run: |
          cd tket/pytket/tests
          pip install -r requirements.txt
      - name: Run tests
        run: cd tket/pytket/tests && pytest --ignore=simulator/

  test_linux_aarch64_wheels:
    name: Test linux aarch64 wheels
    needs: build_Linux_aarch64_wheels
    runs-on: 'buildjet-4vcpu-ubuntu-2204-arm'
    strategy:
      matrix:
        python3-version: ['12']
    steps:
    - uses: actions/checkout@v4
      with:
        path: tket
    - name: Set up Python 3.${{ matrix.python3-version }}
      # Use deadsnakes/action because Python for Linux/ARM is not available with
      # actions/setup-python.
      # Python 3.10 is the default python on Ubuntu 22.04, so this combination
      # is not available from deadsnakes: use the default python in this case.
      if: matrix.python3-version != '10'
      uses: deadsnakes/action@v3.2.0
      with:
        python-version: "3.${{ matrix.python3-version }}"
    - name: Download wheel
      uses: actions/download-artifact@v4
      with:
        name: Linux_aarch64_3.${{ matrix.python3-version }}_wheel
        path: wheelhouse/
    - name: Install wheel
      run: pip install wheelhouse/pytket-*.whl
    - uses: actions/checkout@v4
      with:
        path: tket
    - name: Setup tests
      run: |
        cd tket/pytket/tests
        pip install -U -r requirements.txt
    - name: Run tests
      run: cd tket/pytket/tests && pytest --ignore=simulator/
