# This workflow adds a "stale" label to issues and PRs that have had no activity
# for a specified amount of time, adding a comment to the issue or PR. It does
# not close the issue or PR.
#
# You can adjust the behaviour by modifying this file.
#
# For more information, see: https://github.com/actions/stale

name: Mark stale issues and PRs

on:
  schedule:
  - cron: '15 5 * * *'

jobs:
  stale:
    # Don't run on forks
    if: github.repository == 'CQCL/tket'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
    - uses: actions/stale@v9
      with:
        days-before-issue-stale: 120
        days-before-pr-stale: 30
        days-before-close: -1
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        stale-issue-message: 'This issue has been automatically marked as stale.'
        stale-pr-message: 'This pull request has been automatically marked as stale.'
