#!/bin/bash

# ./test-args <OS> <github-event-type>

set -evx

OS=$1
ET=$2

if [[ $OS = "Linux" ]]; then
    if [[ $ET = "schedule" ]]; then
        echo "[long],~[long]"
    fi
else
    if [[ $ET = "schedule" ]]; then
        echo "[long]~[latex],~[long]~[latex]"
    else
        echo "~[latex]"
    fi
fi
